language: haskell

ghc: 7.8

branches:
  only:
    - master
    - multiparams

addons:
  apt:
    packages:
    - ocaml
    - camlidl

sudo: false

cache:
  apt: true
  directories:
  - $HOME/.cabal
  - $HOME/.ghc

env:
 - SMT=z3 TESTS=Unit/pos
 - SMT=z3 TESTS=Unit/neg
 - SMT=z3 TESTS=Unit/crash
 - SMT=z3 TESTS=Benchmarks/text
 - SMT=z3 TESTS=Benchmarks/bytestring
 - SMT=z3 TESTS=Benchmarks/esop
 - SMT=z3 TESTS=Benchmarks/vect-algs
 - SMT=cvc4 TESTS=Unit/pos
 - SMT=cvc4 TESTS=Unit/neg
 - SMT=cvc4 TESTS=Unit/crash
 - SMT=z3 TESTS=Benchmarks/icfp_pos
 - SMT=z3 TESTS=Benchmarks/icfp_neg
 # ugh... Classify.hs is too slow and makes travis think the build is stalled
 # - TESTS=hscolour

before_install:
 - scripts/travis clean_cache "$SMT"
 - scripts/travis clone_fixpoint

install:
 - scripts/travis install_cabal_deps
 - scripts/travis install_smt "$SMT"

script:
 - scripts/travis do_build && scripts/travis do_test "$TESTS" "$SMT" && scripts/travis test_source_pkg
 - scripts/travis clean_cache "$SMT"

after_failure:
 - scripts/travis dump_fail_logs

